export const USER_LOADING = 'USER_LOADING';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AITH_ERROR';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_REGISTER_MODAL = 'OPEN_REGISTER_MODAL';
export const CLOSE_REGISTER_MODAL = 'CLOSE_REGISTER_MODAL';
export const REGISTER_BUSINESS_SUCCESS  = 'REGISTER_BUSINESS_SUCCESS';
export const REGISTER_BUSINESS_FAIL = 'REGISTER_BUSINESS_FAIL';

export const GET_ALL_CATEGORIES_PENDING = 'GET_ALL_CATEGORIES_PENDING';
export const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';

export const GET_CATEGORY_WISE_SERVICES_PENDING = 'GET_CATEGORY_WISE_SERVICES_PENDING';
export const GET_CATEGORY_WISE_SERVICES_SUCCESS = 'GET_CATEGORY_WISE_SERVICES_SUCCESS';

export const GET_VENDOR_SERVICES = 'GET_VENDOR_SERVICES';
export const GET_VENDOR_SERVICES_FAIL = 'GET_VENDOR_SERVICES_FAIL';

export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';
